wall_line_detection:
  ros__parameters:
    laserscan_topic_sub_name: ["/scan"]
    # laserscan_topic_sub_name: ["/scan", "ydscan_l", "ydscan_r"]
    map_topic_sub_name: "/map"
    laserscan_queue_size: 2
    map_frame: "map"
    base_link_frame: "base_link"
    canny_thr1: 100.0
    canny_thr2: 200.0
    hough_rho: 3.0
    hough_theta: 0.052360 # pi / 180 * N
    hough_thr: 20
    hough_min_line_length: 40.0
    hough_max_line_gap: 10.0
    imshow_wait: 100
    vertical_thr: 6.0
    horizontal_thr: 45
    theta_thr: 0.17453 # pi / 180 * N => (0.017453 * N)
    imshow_map: false
    imshow_laser: false
    imshow_edge: false
    imshow_line: true
    window_type: 0 # nomal=0, autosize=1
    line_distance_max: 2.2


wall_line_test:
  ros__parameters:
    msg_topic_name: "wall_lines_stamped"
    msg_time_tolerance: 0.2
    use_offset: true
    path_offset: 0.5
    only_get_msg_once: false
    action_frequency: 0.1



